# asadmin change-admin-password
# asadmin --port 4848 enable-secure-admin
version: '2'
services:
  db01:
    tty: true
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PW
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - pgdata01:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    links:
      - db01
  java_obj:
    working_dir: /root/
    tty: true
    volumes:
      - .:/home/
    image: openjdk:17-slim-buster
  python_obj:
    working_dir: /root/
    tty: true
    volumes:
      - .:/home
    image: python:3.7.9-stretch
  node_obj:
    working_dir: /root/
    tty: true
    volumes:
      - .:/home/node
    image: node:slim
volumes: 
    pgdata01:
